; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_l432kc]
platform = ststm32
board = nucleo_l432kc
framework = arduino
build_flags =
	-DHAL_CAN_MODULE_ENABLED
	-Wl,-u_printf_float
	-I embedded-pio
	-Wall
	-Wextra
	-Werror=return-type
	-Wno-unused-parameter
	-Wno-missing-field-initializers
lib_extra_dirs = ./embedded-pio
lib_deps = khoih-prog/TimerInterrupt_Generic@^1.13.0
; STM32_CAN comes from embedded-pio/STM32_CAN
